CREATE TABLE TAG (
    ID BIGINT AUTO_INCREMENT NOT NULL,
    DESCRIPTION VARCHAR(100) NOT NULL,
    CONSTRAINT PK_TAG PRIMARY KEY (ID),
    CONSTRAINT U_TAG_DESCRIPTION UNIQUE (DESCRIPTION)
);

CREATE TABLE AUTHOR (
    ID BIGINT AUTO_INCREMENT NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(320) NOT NULL,
    LINKEDIN VARCHAR(100),
    FACEBOOK VARCHAR(100),
    TWITTER VARCHAR(100),
    CONSTRAINT PK_AUTHOR PRIMARY KEY (ID),
    CONSTRAINT U_AUTHOR_NAME UNIQUE (NAME)
);

CREATE TABLE POST (
    ID BIGINT AUTO_INCREMENT NOT NULL,
    TITLE VARCHAR(100) NOT NULL,
    LAST_MODIFIED DATE NOT NULL,
    SUMMARY TEXT NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    URL_POST TEXT NOT NULL,
    CONSTRAINT PK_POST PRIMARY KEY (ID),
    CONSTRAINT U_POST_TITLE UNIQUE (TITLE)
);

CREATE TABLE POST_TAG (
    ID BIGINT AUTO_INCREMENT NOT NULL,
    ID_POST BIGINT NOT NULL,
    ID_TAG BIGINT NOT NULL,
    CONSTRAINT PK_POST_TAG PRIMARY KEY (ID),
    CONSTRAINT U_POST_TAG_FKS UNIQUE (ID_POST, ID_TAG),
    CONSTRAINT FK_POST_TAG_POST FOREIGN KEY (ID_POST) REFERENCES POST (ID),
    CONSTRAINT FK_POST_TAG_TAG FOREIGN KEY (ID_TAG) REFERENCES TAG (ID)
);

CREATE TABLE POST_AUTHOR (
    ID BIGINT AUTO_INCREMENT NOT NULL,
    ID_POST BIGINT NOT NULL,
    ID_AUTHOR BIGINT NOT NULL,
    CONSTRAINT PK_POST_AUTHOR PRIMARY KEY (ID),
    CONSTRAINT U_POST_AUTHOR_FKS UNIQUE (ID_POST, ID_AUTHOR),
    CONSTRAINT FK_POST_AUTHOR_POST FOREIGN KEY (ID_POST) REFERENCES POST (ID),
    CONSTRAINT FK_POST_AUTHOR_AUTHOR FOREIGN KEY (ID_AUTHOR) REFERENCES AUTHOR (ID)
);
