CREATE TABLE TAG (
    ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    DESCRIPTION VARCHAR(100) NOT NULL
);

CREATE TABLE AUTHOR (
    ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    MAIL VARCHAR(50) NOT NULL,
    LINKEDIN VARCHAR(100),
    FACEBOOK VARCHAR(100),
    TWITTER VARCHAR(100)
);

CREATE TABLE POST (
    ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    TITLE VARCHAR(100) NOT NULL,
    LAST_MODIFIED DATE NOT NULL,
    SUMMARY TEXT NOT NULL,
    DESCRIPTION TEXT NOT NULL
);

CREATE TABLE POST_TAG (
    ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    ID_POST BIGINT NOT NULL,
    ID_TAG BIGINT NOT NULL,
    FOREIGN KEY (ID_POST) REFERENCES POST (ID),
    FOREIGN KEY (ID_TAG) REFERENCES TAG (ID)
);

CREATE TABLE POST_AUTHOR (
    ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    ID_POST BIGINT NOT NULL,
    ID_AUTHOR BIGINT NOT NULL,
    FOREIGN KEY (ID_POST) REFERENCES POST (ID),
    FOREIGN KEY (ID_AUTHOR) REFERENCES AUTHOR (ID)
);
